version: 0.2
phases:
  pre_build:
    commands:
      - echo Logiing into Amazon ECR on `date`
      - echo In the pre_build phase...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 557690608558.dkr.ecr.us-east-1.amazonaws.com
      - echo setting repo setting URI...
      - REPOSITORY_URI=557690608558.dkr.ecr.us-east-1.amazonaws.com/customerservice
      - echo setting tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo running mvn clean install
      - mvn clean install
      - echo building the docker image
      - docker build -t $REPOSITORY_URI:latest .
      - echo tagging the docker image
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing docker image to AWWS ECR completed on `date`
      - pushing to repository...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=customerservice
      - echo writing image definition file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo pritting imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json